name: Download

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 12 * * *'

permissions:
  contents: write

env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv sync
        shell: bash

      - name: Run download command
        run: pipenv run python -m download
        shell: bash

      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./repos.csv
          git commit -m "Download repos.csv" && git push || true
        shell: bash